enum ResponseCodes{
    SUCCESS ="SUCCESS",
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED="UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR="INTERNAL_SERVER_ERROR"
}

export default ResponseCodes;